export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FEED: "/feed",
  EXPLORE: "/explore",
  TOPICS: "/topics",
  WELCOME: "/welcome",
  CHAT: "/chat",
  TOPIC: (slug: string) => `/topics/${slug}`,
  PROFILE: (username: string) => `/profile/${username}`,
  POST: (id: string) => `/posts/${id}`,
  EDIT_POST: (id: string) => `/posts/${id}/edit`,
  ANIME_LIST: "/anime",
  ANIME_DETAIL: (id: string | number) => `/anime/${id}`,
  MANGA_LIST: "/manga",
  MANGA_DETAIL: (id: string | number) => `/manga/${id}`,
  MANGA_DASHBOARD: "/manga/dashboard",
  MANGA_UPLOAD: "/manga/upload",
  MANGA_UPLOAD_BY_ID: (id: string) => `/manga/${id}/upload`,
  MANGA_MODERATION: "/manga/moderation",
  POPULAR: "/popular",
  COMMUNITIES: "/communities",
  HELP: "/help",
  BLOG: "/blog",
  ABOUT: "/about",
  RANKINGS: "/rankings",
  NEWS: "/news",
} as const;
