application:
  title: Otaku Community
  version: 1.0.0

spring:
  application:
    name: otaku-community-backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 300MB

server:
  port: ${PORT:8080}
  servlet:
    context-path:

# Auth0 Configuration
auth0:
  audience: ${AUTH0_AUDIENCE}
  domain: ${AUTH0_DOMAIN}

okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER_NAME}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL}
  pagination:
    default-page-size: 20
    max-page-size: 100
  upload:
    max-images-per-post: 4
    max-image-size: 15728640 # 15MB in bytes
  rate-limit:
    enabled: true
    requests-per-minute: 100

# Logging
logging:
  level:
    root: INFO
    com.otaku.community: DEBUG
    org.springframework.web: INFO
#    org.springframework.web.socket: TRACE
#    org.springframework.web.socket.server.support: TRACE
#    org.springframework.web.socket.sockjs: TRACE
#    org.springframework.messaging: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

default:
  avatar:
    url: https://res.cloudinary.com/dfdwupiah/image/upload/v1767623060/otaku-community/avatar_qmmxgm.png
