spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.otaku.community: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
